version: '3'
services:
  rails:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ".:/root/rails-docker"
    working_dir: /root/rails-docker
    entrypoint: bash -c "rails server -b 0.0.0.0"

  react:
    build: ./ui
    ports:
      - "8080:8080"
    volumes:
      - "./ui:/root/react-docker"
    working_dir: /root/react-docker
    entrypoint: bash -c "npm run fmt && npm start"
