version: '3'
services:
  rails:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ".:/root/rails-docker"
    working_dir: /root/rails-docker
    environment:
      - DATABASE_HOST=spocon-mysql
      - DATABASE_PORT=3306
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=mysql
    entrypoint: bash -c "rm -f tmp/pids/server.pid && rails server -b 0.0.0.0" #tmp/pids/server.pidが残っているとrailsを起動できないため､削除して起動する

  rails-test:
    build: .
    ports:
      - "3001:3001"
    volumes:
      - ".:/root/rails-docker"
    working_dir: /root/rails-docker
    environment:
      - DATABASE_HOST=spocon-test-mysql
      - DATABASE_PORT=3307
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=mysql

  react:
    build: ./ui
    ports:
      - "8080:8080"
    volumes:
      - "./ui:/root/react-docker"
    working_dir: /root/react-docker
    entrypoint: bash -c "npm run fmt && npm start"

  mysql:
    image: mysql:8
    container_name: spocon-mysql
    volumes:
      - ./docker/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=mysql

  test-mysql:
    image: mysql:8
    container_name: spocon-test-mysql
    volumes:
      - ./docker/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
    ports:
      - "3307:3306"
    expose:
      - 3307
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_TCP_PORT=3307
