version: '3'
services:
  rails:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ".:/root/rails-docker"
    working_dir: /root/rails-docker
    entrypoint: bash -c "rails server -b 0.0.0.0"

  mysql:
    image: mysql:8
    volumes:
      - ./docker/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
