version: '3'
services:
  rails:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ".:/root/rails-docker"
    working_dir: /root/rails-docker
    entrypoint: bash -c "rails server -b 0.0.0.0"
