version: '3'
services:
  rails:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ".:/root/play-rails"
    working_dir: /root/play-rails
    entrypoint: bash -c "rails server -b 0.0.0.0"
